baseURL = "https://blog.cristianrz.eu.org/"
title = "cristianrz"
theme = "hugo-paper"
copyright = "© 2026 cristianrz"
languageCode = "en"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableInlineShortcodes = true

[pagination]
  pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  codeFences = true
  noClasses = false

[params]
  color = 'gray'
  dateFormat = "02 Jan 2006"
  readingTime = true
  name = 'cristianrz'
  github = 'cristianrz'

[menu]
  [[menu.main]]
    identifier = "cool-services"
    name = "Cool services"
    url = "/pages/cool-services/"
    weight = 10
